---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidygeocoder)
library(dplyr)
```


```{r}
nfl_df<-data.frame(read_csv("nfl_games.csv"))
cfb_df<- data.frame(read_csv("cfb_games.csv"))
```

```{r}
nfl_df_2<-nfl_df[,c("game_id","season","gameday","gametime","away_team","home_team","roof","stadium")]
nfl_df_2<-nfl_df_2[nfl_df_2$gameday>Sys.Date(),]

cfb_df$date_clean<-as.Date(substr(cfb_df$date,5,length(cfb_df$date)),format="%b %d")

colnames(nfl_df_2)<-paste0("nfl_",colnames(nfl_df_2))
colnames(cfb_df)<-paste0("cfb_",colnames(cfb_df))
```

```{r}
merge_df<-merge(cfb_df,nfl_df_2,all=TRUE)
merge_df$date_gap<-abs(merge_df$cfb_date_clean-merge_df$nfl_gameday)

merge_df_2<-merge_df[merge_df$date_gap<2,]

```

```{r}
location_df<-data.frame(c(unique(merge_df_2$cfb_location),unique(merge_df_2$nfl_stadium)))
colnames(location_df)<-"stadium"

location_df<-location_df %>% geocode(stadium) 

write.csv(location_df,"location_df.csv",row.names = FALSE)

location_override_df<-data.frame(read_csv("location_df_override_V01.csv"))

colnames(location_override_df)<-c("stadium","manual_lat","manual_long")
colnames(location_df)<-c("stadium","auto_lat","auto_long")

full_loc_df<-merge(location_df,location_override_df,by.x="stadium",by.y="stadium",all.x=TRUE)
full_loc_df$lat<-coalesce(full_loc_df$manual_lat,full_loc_df$auto_lat)
full_loc_df$long<-coalesce(full_loc_df$manual_long,full_loc_df$auto_long)

full_loc_df<-full_loc_df[,c("stadium","lat","long")]
```

